<?php
/**
 * Created by PhpStorm.
 * User: coutinho
 * Date: 2/13/19
 * Time: 1:19 PM
 */
$status = adminController::$validCredentials;

?>
<div style="">
    <div class="row">
        <nav class="navbar navbar-static-top navbar-custom" role="navigation">
            <div class="container-fluid ">
                <ul class="nav navbar-nav navbar-right">
                    <li><a style="color: white" href="#"><span class="fa fa-user-plus"></span> Sign up</a></li>
                    &nbsp;&nbsp;&nbsp;
                </ul>
            </div>
        </nav>
    </div>
    <hr>

    <div class="login-wrapper">
        <form action="/admin/login" method="post" class="form-signin">
            <h5 class="form-signin-heading" style="text-align: center">Sign in</h5>
            <input type="text" class="form-control flat-in " name="username" placeholder="username" required>
            <input type="password" class="form-control flat-in" name="password" placeholder="password" required>
            <button type="submit" name="login" class="btn btn-primary btn-block flat-in">login</button>
            <div class="<?= !empty($status) ? 'alert alert-danger text-center' : '' ?> "
                 style="border-radius: 0; margin-top: 2px"><?= $status ?></div>
        </form>

    </div>

</div>


</div>
