<?php
/**
 * Created by PhpStorm.
 * User: coutinho
 * Date: 4/30/19
 * Time: 1:49 PM
 */
require_once TEMP . 'top-bar2.phtml';
require_once TEMP . 'private-nav.phtml';
//retrieving the client loan Data
$repayment = $this->view_data['repayment'];
$arrears = $this->view_data['arrears'];

?>

<div class="container">
    <div class="console">
        <br>
        <h4>View Client: <?php echo $this->view_data['clients'][0]['firstname']." ".$this->view_data['clients'][0]['maiden']." ".$this->view_data['clients'][0]['surname']. " ".$this->view_data['clients'][0]['name']?> </h4>
        <hr style="border: none;height: 3px;color: #204d74;background-color: #204d74"
        <div class="vclient-wrapper">
            <div class="view-client">
                <h5 style="text-align: center"> View Client </h5>
                <hr style="height: 3px; color: #1c7430; background-color: #1c7430">

                <div class="table-responsive">
                    <h5>Repayment History</h5>
                    <table class="table">
                        <tr>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Amount </th>
                            <th>Installment</th>
                            <th>Collector</th>
                        </tr>

                        <tr>
                            <?php foreach ($repayment as $payment): ?>
                                <td><?php echo $payment['date'] ?></td>
                                <td><?php echo $payment['time'] ?></td>
                                <td><?php echo $payment['amount'] ?></td>
                                <td><?php echo $payment['installment'] ?></td>
                                <td><?php echo $payment['collector'] ?></td>
                        </tr>
                            <?php endforeach;?>

                    </table>
                </div>
            </div>
            <br>
            <div class="view-client">
                <h5 style="text-align: center"> View Client </h5>
                <hr style="height: 3px; color: #d9534f; background-color: #d9534f">

                <div class="table-responsive">
                    <h5>Arrears History</h5>
                    <table class="table">
                        <tr>
                            <th>Date</th>
                            <th>loanID</th>
                            <th>Amount </th>
                            <th>Installment</th>
                            <th>Explanation</th>
                        </tr>

                        <tr>
                            <?php foreach ($arrears as $arrear): ?>
                            <td><?php echo $arrear['date'] ?></td>
                            <td><?php echo $arrear['loanID'] ?></td>
                            <td><?php echo $arrear['amount'] ?></td>
                            <td><?php echo $arrear['instalment'] ?></td>
                            <td><?php echo "N/A" ?></td>
                        </tr>
                        <?php endforeach;?>

                    </table>
                </div>
            </div>


        </div>
    </div>
</div>

