<?php
/**
 * Created by PhpStorm.
 * User: coutinho
 * Date: 2/14/19
 * Time: 1:56 PM
 */
?>

<nav class="navbar navbar-default" style="background-color: #204d74; border-radius: 4px; border-top: solid 5px #204d74">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class=""><a href="/accounts/home">Home</a></li>
            <li><a href="/accounts/expense">Expenditures</a></li>
            <li><a href="/accounts/credit">Income</a></li>
        </ul>

    </div>
</nav>