<?php
/**
 * Created by PhpStorm.
 * User: coutinho
 * Date: 2/17/19
 * Time: 10:57 AM
 */
?>
<nav class="navbar navbar-default" style="background-color: #204d74; border-radius: 4px; border-top: solid 5px #204d74">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class=""><a href="/admin/home">Home</a></li>
            <li><a href="/admin/disbursement">Disbursement</a></li>
            <li><a href="/admin/administration">Administration</a></li>
            <li><a href="/admin/client">Clients</a></li>
            <li><a href="/admin/preferences">Preferences</a></li>
            <li><a href="/admin/zone">Zone</a></li>
            <li><a href="/admin/messages">messages</a></li>
            <li><a href="/admin/setup">Set up</a></li>
        </ul>


    </div>
</nav>