<?php
/**
 * Created by PhpStorm.
 * User: coutinho
 * Date: 2/12/19
 * Time: 2:09 PM
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?php echo "loanMS v2.0" ?></title>
    <link rel="shortcut icon" href="/webkit/img/top2.ico" type="image/png">

    <link rel="stylesheet" href="/webkit/lib/bs/bootstrap-3.7-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/webkit/fonts/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="/webkit/lib/fontawesome-free-5.7.2-web/css/all.css">
    <link rel="stylesheet" href="/webkit/css/font-awesome.min.css">
    <script src="/webkit/lib/js/jquery.min.js"></script>
    <script src="/webkit/lib/bs/bootstrap-3.7-dist/js/bootstrap.min.js"></script>
    <script src="/webkit/lib/js/bootbox.min.js"></script>
    <script src="/webkit/lib/js/Chart.js"></script>
    <script src="/webkit/js/main.js"></script>

<!--    -->
<!--    CkEdit Data-->
<!--    <script src="/webkit/lib/ckeditor/ckeditor.js"></script>-->
<!--    <script src="/webkit/lib/ckeditor/samples/js/sample.js"></script>-->
<!--    <link rel="stylesheet" href="/webkit/lib/ckeditor/samples/css/samples.css">-->
<!--    <link rel="stylesheet" href="/webkit/lib/ckeditor/samples/toolbarconfigurator/lib/codemirror/neo.css">-->

    <link rel="stylesheet" href="/webkit/css/main.css">
</head>
<body >

<div id="" style=" height: 90%">
