<?php
/**
 * Created by PhpStorm.
 * User: coutinho
 * Date: 2/14/19
 * Time: 1:56 PM
 */
?>

<nav class="navbar navbar-default" style="background-color: #204d74; border-radius: 4px; border-top: solid 5px #204d74">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class=""><a href="/private/home">Home</a></li>
            <li><a href="/private/group">Client Groups</a></li>
            <li><a href="/private/registration">Registration</a></li>
            <li><a href="/private/disbursement">Disbursment</a></li>
            <li><a href="/private/collection">Collection</a></li>
            <li><a href="/private/views">View</a></li>
            <li><a href="/private/par">Par</a></li>
        </ul>

    </div>
</nav>