<?php
/**
 * Created by PhpStorm.
 * User: coutinho
 * Date: 2/17/19
 * Time: 10:56 AM
 */
?>
<nav class="navbar navbar-custom" role="navigation" style="margin-left: 1px; margin-right: 1px; border-radius: 0; border: none">
    <div class="container-fluid">
        <div class="navbar-header">
            <p> Loan Management System</p>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" style="background-color: #2e6da4; color: #ced4da; border: solid 1px #2e6da4" type="button" id="menu1" data-toggle="dropdown"><?php echo Session::get('loggedIn') ?>
                    <img src="/webkit/img/Icons/user_male_circle_filled_50px.png" height="30px" alt="user"><span class="caret"></span></button>
                <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/private/pchange">Change password</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="/private/logout">logout</a></li>
                    <li role="presentation" class="divider"></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">About Us</a></li>
                </ul>
            </div>
        </ul>


</nav>

