<?php
/**
 * Created by PhpStorm.
 * User: coutinho
 * Date: 4/30/19
 * Time: 2:15 PM
 */
require_once TEMP.'top-bar2.phtml';
require_once TEMP.'private-nav.phtml';
//var_dump(Session::get('loggedIn'));
?>

<div class="container">
    <div class="console">
        <br>
        <h4>PAR (private)</h4>
        <hr style="border: none;height: 3px;color: #204d74;background-color: #204d74">
        <div class="row">
            <div class="col-sm-4"></div>
            <div class="col-sm-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title" style="text-align: right"> Portfolio At Risk </h5>
                    </div>
                    <div class="panel-body">
                        <h6>Today </h6>
                        <canvas id="daily-summary-canvas" style="width: 300px; height: 100px"></canvas>
                        <br><br>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
